---

- name: Remove rancher-backup chart
  kubernetes.core.helm:
    name: "{{ helm_rancher_backup_name }}"
    release_namespace: "{{ helm_rancher_backup_release_namespace }}"
    state: absent
    wait: "{{ helm_rancher_backup_wait }}"
    binary_path: "{{ helm_rancher_backup_binary_path }}"
    context: "{{ helm_rancher_backup_context }}"
    kubeconfig: "{{ helm_rancher_backup_kubeconfig }}"
    validate_certs: "{{ helm_rancher_backup_validate_certs }}"
  ignore_errors: True

- name: Remove rancher-backup-cdr chart
  kubernetes.core.helm:
    name: "{{ helm_rancher_backup_name }}-cdr"
    release_namespace: "{{ helm_rancher_backup_release_namespace }}"
    state: absent
    wait: "{{ helm_rancher_backup_wait }}"
    binary_path: "{{ helm_rancher_backup_binary_path }}"
    context: "{{ helm_rancher_backup_context }}"
    kubeconfig: "{{ helm_rancher_backup_kubeconfig }}"
    validate_certs: "{{ helm_rancher_backup_validate_certs }}"
  ignore_errors: True

- name: List helm release secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    namespace: "{{ helm_rancher_backup_release_namespace }}"
  register: secret_list

- name: List of helm release secret
  set_fact:
    helm_release_secret_list: "{{ secret_list['resources'] | map(attribute='metadata')  | map(attribute='name') | map('regex_search','.*helm.*rancher-backup.*') | select('string') | list }}"

- name: delete list release secret
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Secret
    namespace: "{{ helm_rancher_backup_release_namespace }}"
    name: "{{ item }}"
  with_items: "{{ helm_release_secret_list }}"