---
- name: "Deploy rancher_backup-crd chart"
  frantchenco.helm_wrapper.install:
    name: "{{ helm_rancher_backup_name }}-crd"
    chart_repo_url: "{{ helm_rancher_backup_chart_repo_url }}"
    chart_version: "{{ helm_rancher_backup_chart_version }}"
    chart_ref: "{{ helm_rancher_backup_chart_ref }}-crd"
    release_namespace: "{{ helm_rancher_backup_release_namespace }}"
    create_namespace: "{{ helm_rancher_backup_create_namespace }}"
    values: "{{ helm_rancher_backup_values | to_json }}"
    values_files: "{{ helm_rancher_backup_values_files }}"
    wait: "{{ helm_rancher_backup_wait }}"
    disable_hook: "{{ helm_rancher_backup_disable_hook }}"
    force: "{{ helm_rancher_backup_force }}"
    atomic: "{{ helm_rancher_backup_atomic }}"
    skip_crds: "{{ helm_rancher_backup_skip_crds }}"
    update_repo_cache: "{{ helm_rancher_backup_update_repo_cache }}"
    binary_path: "{{ helm_rancher_backup_binary_path }}"
    context: "{{ helm_rancher_backup_context }}"
    kubeconfig: "{{ helm_rancher_backup_kubeconfig }}"
    validate_certs: "{{ helm_rancher_backup_validate_certs }}"

- name: "Deploy rancher_backup chart"
  frantchenco.helm_wrapper.install:
    name: "{{ helm_rancher_backup_name }}"
    chart_repo_url: "{{ helm_rancher_backup_chart_repo_url }}"
    chart_version: "{{ helm_rancher_backup_chart_version }}"
    chart_ref: "{{ helm_rancher_backup_chart_ref }}"
    release_namespace: "{{ helm_rancher_backup_release_namespace }}"
    create_namespace: "{{ helm_rancher_backup_create_namespace }}"
    values: "{{ helm_rancher_backup_values | to_json }}"
    values_files: "{{ helm_rancher_backup_values_files }}"
    wait: "{{ helm_rancher_backup_wait }}"
    disable_hook: "{{ helm_rancher_backup_disable_hook }}"
    force: "{{ helm_rancher_backup_force }}"
    atomic: "{{ helm_rancher_backup_atomic }}"
    skip_crds: "{{ helm_rancher_backup_skip_crds }}"
    update_repo_cache: "{{ helm_rancher_backup_update_repo_cache }}"
    binary_path: "{{ helm_rancher_backup_binary_path }}"
    context: "{{ helm_rancher_backup_context }}"
    kubeconfig: "{{ helm_rancher_backup_kubeconfig }}"
    validate_certs: "{{ helm_rancher_backup_validate_certs }}"