---
- name: Deploy rancher_backup chart
  ansible.builtin.import_tasks: install.yaml

- name: Configure backup s3 and encryption
  ansible.builtin.import_tasks: configure_backup_s3_and_encryption.yaml

- name: Try to restore if configure rancher
  ansible.builtin.import_tasks: restore_rancher_from_backup.yaml

- name: Configure backup policy
  ansible.builtin.import_tasks: configure_backup_policy.yaml
